# Generated by Django 4.1.5 on 2023-01-07 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 7, 19, 37, 19, 467204, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_by', models.CharField(max_length=100)),
                ('choice', models.CharField(max_length=100)),
                ('ques', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polling.question')),
            ],
        ),
    ]
