# Generated by Django 4.1.5 on 2023-01-07 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_question_date_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 7, 19, 53, 34, 827956, tzinfo=datetime.timezone.utc)),
        ),
    ]
