# Generated by Django 4.1.5 on 2023-01-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0004_alter_question_date_alter_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='ques',
            field=models.CharField(max_length=1000),
        ),
    ]
