# Generated by Django 4.1.5 on 2023-01-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0005_alter_answer_ques'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answered_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
